### ISSUE TITLE
"sudo ipmctl show -region":Command not run. 

### ISSUE THREAD

**Issue by luckyq** [intel/ipmctl#197] opened 2022-10-04 06:45 UTC
Hi, All.

I have encountered a problem after I reinstall the linux system.

I have a optane machine:
![Screen Shot 2022-10-02 at 3 59 15 PM](https://user-images.githubusercontent.com/13534344/193480092-27f6480e-2e67-488b-851c-666e244fba6a.png)

Before I reinstall the linux. It works well.

But now, when I want to configure it into numa mode.

This is the error.
```
sudo ipmctl show -region
Show region failed: Error 2 - Command not run
```
```
@optane04:~$ sudo ipmctl delete -goal
Error: Unable to complete operation due to existing PCD Configuration partition corruption. Use create -f -goal to override current PCD and create goal.
Delete memory allocation goal failed: Error 105 - The configuration data is invalid or unrecognized.
```
I also tried some solutions: 
ipmctl delete -f -dimm -pcd
![Screen Shot 2022-10-03 at 11 43 59 PM](https://user-images.githubusercontent.com/13534344/193751950-8cdc3ef0-c785-43b6-bd25-7bd7cd51f7ed.png)

I also run other command:

sudo ipmctl show -dimm

![Screen Shot 2022-10-03 at 11 40 41 PM](https://user-images.githubusercontent.com/13534344/193751303-4769ec7b-971f-456d-b10c-545886e319a4.png)

sudo ipmctl start -diagnostic

![Screen Shot 2022-10-03 at 11 41 45 PM](https://user-images.githubusercontent.com/13534344/193751497-df293619-5724-417d-815b-a9bbcacfeaa4.png)

Could anyone help me to solve this problem?

Thanks in advance.

**Comment by nolanhergert** [comment] 2022-10-04 16:29
Can you run "ipmctl create -f -goal" and report back? If it doesn't work, try adding "ipmctl delete -pcd" beforehand.

**Comment by luckyq** [comment] 2022-10-04 19:05
> 
<img width="1337" alt="Screen Shot 2022-10-04 at 12 04 35 PM" src="https://user-images.githubusercontent.com/13534344/193904338-5f10b440-898d-4dc2-bbb3-e568e643acb8.png">

The first cmd seems work well.

But still we can not create a goal.

**Comment by nolanhergert** [comment] 2022-10-04 20:52
Interesting. I'm going to repeat that error for future searchers:
"Create region configuration goal failed: Error 112 - Platform does not support changing configuration through management software"

  * Can you run "ipmctl show -system PCAT" and paste the output?
  * What version of ipmctl are you running? "ipmctl version". Newer versions of ipmctl contain a few fixes. https://github.com/intel/ipmctl/releases/

**Comment by luckyq** [comment] 2022-10-04 21:06
This is the results of "ipmctl show -system PCAT":

<img width="556" alt="Screen Shot 2022-10-04 at 2 05 25 PM" src="https://user-images.githubusercontent.com/13534344/193928596-5da92ca0-c3ee-40ad-a180-151731beca70.png">

The ipmctl version is 

<img width="864" alt="Screen Shot 2022-10-04 at 2 06 13 PM" src="https://user-images.githubusercontent.com/13534344/193928722-059d38b0-40ee-4a79-8cc1-fa21c880ab85.png">


Seems the ACPI table is the error.

Do you know how to reinitialize it?

**Comment by nolanhergert** [comment] 2022-10-04 21:20
Yeah, we add support for that in 3794. If your distro doesn't have that version or newer, you can download the latest 2.* ipmctl version, 3885, from the link above.

**Comment by StevenPontsler** [comment] 2022-10-04 21:33
I think trying a newer version of ipmctl makes sense.

What distro and version of that distro are you using?

**Comment by luckyq** [comment] 2022-10-04 22:08
> * ipmctl show -system PCAT

I just reinstall the newer version which is 02.00.00.3885.
But when I run the binary, 

<img width="1436" alt="Screen Shot 2022-10-04 at 3 07 13 PM" src="https://user-images.githubusercontent.com/13534344/193939035-7e7cb801-a737-4f35-ab68-e389bee94f1d.png">


It seems still the 3709. I download the source code for the above link.


And it has the same error as before.

**Comment by luckyq** [comment] 2022-10-04 22:14
> 



> I think trying a newer version of ipmctl makes sense.
> 
> What distro and version of that distro are you using?

LInux version: ubuntu 20.04 server LTS.
Linux pasa 5.4.0-126-generic #142-Ubuntu

**Comment by luckyq** [comment] 2022-10-04 22:28
I just solved the problem by remove libipmctl4 and also install acpid. (I am not sure which one should be the reason. But it works now.)
Everything goes well.

it seems libipmctl4 is the problem. 
It should be installed with ndctl or ipmctl when I used apt install.
<img width="1046" alt="Screen Shot 2022-10-04 at 3 26 31 PM" src="https://user-images.githubusercontent.com/13534344/193941624-ca84fd40-fd6c-47c4-9b20-6298db3e92e0.png">




After I remove this lib. Everything goes well.


<img width="901" alt="Screen Shot 2022-10-04 at 3 25 00 PM" src="https://user-images.githubusercontent.com/13534344/193941338-a55284e8-9a5e-47e3-a273-0e17f2b58dea.png">

I hope this will help if someone also uses "sudo apt install ipmctl " and get the errors like mine.

**Comment by StevenPontsler** [comment] 2022-10-04 22:35
Thanks for the follow up. I was just going to suggest trying binaries from newer Ubuntu releases.

I would guess it is the acpid that changed things as it looked to me like ipmctl was having trouble with the ACPI tables.

If the issue is resolved please close it.

**Closed** 2022-10-04 22:43 UTC

**Comment by nolanhergert** [comment] 2022-10-04 23:08
Weird. My guess is that the newer libipmctl distributed with the executable was not getting used. Removing libipmctl4 forced it to use the proper one? Anyways, glad it's working.
