### ISSUE TITLE
ipmctl dump very slow 

### ISSUE THREAD

**Issue by pradeep-bose** [intel/ipmctl#94] opened 2019-04-01 10:34 UTC
ipmctl dump -destination /tmp/ipmctl_output_20190401_065521_1554119721_52 -support 
command takes close to 20 mins to dump the file for a fully populated server on linux. 

Please include some kind of parallelization in the code so that , the operation get completed faster

**Comment by gldiviney** [comment] 2019-04-01 12:33
Thanks - we'll look for opportunities to make this process faster. There are some constraints which are beyond our control, but we will analyze.

**Comment by sscargal** [comment] 2019-04-02 20:40
On a fully populated 2-socket system with 32GB DDR DIMMs and 256GB DCPM Modules running Fedora 29 (4.20.16-200.fc29.x86_64), the ipmctl support dump takes 10-12seconds.  Please make sure are using recent versions of ipmctl, BIOS, DCPM Firmware, and Kernel.

**Comment by pradeep-bose** [comment] 2019-04-03 07:24
ipmctl version - v01.00.00.3440
for 4 DCPMM - 4 minutes 
For 7 DCPMM -10 minutes 
for 24 DCPMM - 20 minutes 
kernel SLES 12 SP4 4.12 
RHEL 7.6 3.10.0-957.5.1.el7.x86_64 
BIOS & Firmware are latest 
anyways intent is get some parallelization   in the code where possible

**Comment by nolanhergert** [comment] 2021-05-03 21:42
We are not able to reproduce, nor are we able to currently commit time to fixing this issue. Closing.

**Closed by nolanhergert** 2021-05-03 21:42 UTC
Labels: enhancement
